spring.application.name=inventory
server.port=8083
server.servlet.context-path=/inventory
springdoc.api-docs.path=/openapi
springdoc.swagger-ui.path=/docs

# Configuración de H2
spring.datasource.url=jdbc:h2:mem:inventorydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.settings.web-allow-others=true

# Configuración Resilience4j
resilience4j.circuitbreaker.instances.inventoryService.registerHealthIndicator=true
# Si el 50% de las llamadas fallan, se abre el circuito
resilience4j.circuitbreaker.instances.inventoryService.failureRateThreshold=50
# Tiempo de espera antes de intentar reconectar
resilience4j.circuitbreaker.instances.inventoryService.waitDurationInOpenState=5000